"""Initial migration with core models

Revision ID: 001
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FINANCE_MANAGER', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table('cloud_providers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.Enum('AWS', 'GCP', 'AZURE', 'OTHER', name='providertype'), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cloud_providers_type_active', 'cloud_providers', ['provider_type', 'is_active'], unique=False)
    
    op.create_table('budgets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_type', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', 'PROJECT', name='budgettype'), nullable=False),
    sa.Column('scope_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budgets_active_dates', 'budgets', ['is_active', 'start_date', 'end_date'], unique=False)
    
    op.create_table('system_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configurations_key'), 'system_configurations', ['key'], unique=True)
    
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    
    op.create_table('budget_alerts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('budget_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('current_spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('alert_type', sa.Enum('THRESHOLD', 'FORECAST', 'ANOMALY', name='alerttype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_alerts_budget_ack', 'budget_alerts', ['budget_id', 'acknowledged'], unique=False)
    op.create_index(op.f('ix_budget_alerts_budget_id'), 'budget_alerts', ['budget_id'], unique=False)
    
    op.create_table('cost_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('usage_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_data_provider_date', 'cost_data', ['provider_id', 'cost_date'], unique=False)
    op.create_index('ix_cost_data_resource_date', 'cost_data', ['resource_id', 'cost_date'], unique=False)
    op.create_index('ix_cost_data_service_date', 'cost_data', ['service_name', 'cost_date'], unique=False)
    op.create_index('ix_cost_data_tags_gin', 'cost_data', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_cost_data_provider_id'), 'cost_data', ['provider_id'], unique=False)
    op.create_index(op.f('ix_cost_data_resource_id'), 'cost_data', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_data_resource_type'), 'cost_data', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cost_data_service_name'), 'cost_data', ['service_name'], unique=False)
    op.create_index(op.f('ix_cost_data_cost_date'), 'cost_data', ['cost_date'], unique=False)
    
    op.create_table('optimization_recommendations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('recommendation_type', sa.Enum('RIGHTSIZING', 'RESERVED_INSTANCE', 'UNUSED_RESOURCE', 'UNDERUTILIZED', name='recommendationtype'), nullable=False),
    sa.Column('current_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('optimized_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('potential_savings', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('implementation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IMPLEMENTED', name='recommendationstatus'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['cloud_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_optimization_provider_status', 'optimization_recommendations', ['provider_id', 'status'], unique=False)
    op.create_index('ix_optimization_type_savings', 'optimization_recommendations', ['recommendation_type', 'potential_savings'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_provider_id'), 'optimization_recommendations', ['provider_id'], unique=False)
    op.create_index(op.f('ix_optimization_recommendations_resource_id'), 'optimization_recommendations', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_recommendations_resource_id'), table_name='optimization_recommendations')
    op.drop_index(op.f('ix_optimization_recommendations_provider_id'), table_name='optimization_recommendations')
    op.drop_index('ix_optimization_type_savings', table_name='optimization_recommendations')
    op.drop_index('ix_optimization_provider_status', table_name='optimization_recommendations')
    op.drop_table('optimization_recommendations')
    op.drop_index(op.f('ix_cost_data_cost_date'), table_name='cost_data')
    op.drop_index(op.f('ix_cost_data_service_name'), table_name='cost_data')
    op.drop_index(op.f('ix_cost_data_resource_type'), table_name='cost_data')
    op.drop_index(op.f('ix_cost_data_resource_id'), table_name='cost_data')
    op.drop_index(op.f('ix_cost_data_provider_id'), table_name='cost_data')
    op.drop_index('ix_cost_data_tags_gin', table_name='cost_data')
    op.drop_index('ix_cost_data_service_date', table_name='cost_data')
    op.drop_index('ix_cost_data_resource_date', table_name='cost_data')
    op.drop_index('ix_cost_data_provider_date', table_name='cost_data')
    op.drop_table('cost_data')
    op.drop_index(op.f('ix_budget_alerts_budget_id'), table_name='budget_alerts')
    op.drop_index('ix_budget_alerts_budget_ack', table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_system_configurations_key'), table_name='system_configurations')
    op.drop_table('system_configurations')
    op.drop_index('ix_budgets_active_dates', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_cloud_providers_type_active', table_name='cloud_providers')
    op.drop_table('cloud_providers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###